App:
  URL: http://10.0.119.208/
  LogSavePath: D:/tpcs/logs
  LogFileName: app
  LogFileExt: .log
  UploadDir: D:/tpcs
  FileUploadPath: D:/tpcs/uploads
  MdImgUploadPath: D:/tpcs/files
  SessionNames:
    - user
    - upload_status
Server:
  RunMode: release
  HttpPort: 8080
  ReadTimeout: 60
  WriteTimeout: 60
Database:
  DBType: mysql
  Username: root
  Password: 1234
  Host: 127.0.0.1:3306
  DBName: tpcs_go
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
Redis:
  Addr: 127.0.0.1:6379
  Password: 19834044876
  DB: 0
  Topic: register
Email:
  Host: smtp.qq.com
  Port: 465
  UserName: 1696589321@qq.com
  Password: reivzpjdtrffcjdc
  IsSSL: true
  From: 1696589321@qq.com
  To:
    - lipeiyang1024@163.com
JWT:
  Key: philpy~!@#$%^&*()_+
  Secret: philpy+_)(*&^%$#@!~
  Issuer: tpcs
  Expire: 300